defaults:

  upload-hunter-cache: &upload-hunter-cache
    run:
      name: "Upload Hunter cache"
      working_directory: ~/build
      command: |  # Upload Hunter cache if not PR build.
        if [ ! "$CIRCLE_PR_NUMBER" ]; then
          cmake --build . --target hunter_upload_cache
        fi

  environment-info: &environment-info
    run:
      name: "Environment info"
      command: |
        echo CXX: $CXX
        $CXX --version
        $CXX --version > compiler.version

  configure: &configure
    run:
      name: "Configure"
      # Build "out-of-source" to have better coverage report
      # (ninja is using relative paths otherwise).
      working_directory: ~/build
      command: |
        cmake ../project -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCOVERAGE=OFF $CMAKE_OPTIONS

  configureMac: &configureMac
    run:
      name: "ConfigureMac"
      working_directory: ~/build
      command: |
        cmake ../project -DCMAKE_BUILD_TYPE=$BUILD_TYPE $CMAKE_OPTIONS -DCMAKE_TOOLCHAIN_FILE=~/project/toolchain.cmake

  build: &build
    run:
      name: "Build"
      working_directory: ~/build
      command: make -j $BUILD_PARALLEL_JOBS

  linuxInstallGO: &linuxInstallGO
    run:
      name: "LinuxInstallGO and Tests"
      working_directory: ~/project
      command: |
          curl -L --output go1.20.linux-amd64.tar.gz "https://dl.google.com/go/go1.20.linux-amd64.tar.gz"
          tar -xf go1.20.linux-amd64.tar.gz
          sudo mv go /usr/local
          sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
          git clone --depth 1 https://github.com/ethereum/go-ethereum.git
          git clone --depth 1 https://github.com/ethereum/tests.git
          cd go-ethereum
          make all
          sudo ln -s ~/project/go-ethereum/build/bin/evm /usr/local/bin/evm

  test-retesteth: &test-retesteth
    run:
      name: "Test-retesteth"
      working_directory: ~/build/retesteth
      command: |
        ./retesteth -t GeneralStateTests/stExample -- --testpath ~/project/tests
        ./retesteth -t BlockchainTests/ValidBlocks/bcExample -- --testpath ~/project/tests
        ./retesteth -t GeneralStateTests -- --checkhash --testpath ~/project/tests
        ./retesteth -t BlockchainTests -- --checkhash --testpath ~/project/tests

  test: &test
    run:
      name: "Test"
      working_directory: ~/build/retesteth
      command: |
        if [ $(uname) = Linux ]; then
          export TMPDIR=/dev/shm
        fi
        ./retesteth -t TestHelperSuite
        ./retesteth -t EthObjectsSuite
        ./retesteth -t DataObjectTestSuite
        ./retesteth -t OptionsSuite
        ./retesteth -t ExpectSectionSuite
        ./retesteth -t StructTest
        ./retesteth -t MemoryLeak
#        ./retesteth -t LLLCSuite
#        ./retesteth -t trDataCompileSuite
#        git clone --depth 1 https://github.com/ethereum/tests.git
#        export ETHEREUM_TEST_PATH=~/build/testeth/tests
#        ctest --output-on-failure -j $TEST_PARALLEL_JOBS

  store-retesteth: &store-retesteth
    store_artifacts:
      path: ~/build/retesteth
      destination: retesteth

  store-log: &store-log
    store_artifacts:
      path: /home/builder/build/deps/src/secp256k1-stamp
      destination: log


  upload-coverage-data: &upload-coverage-data
    run:
      name: "Upload coverage data"
      command: |
        pwd
        $GCOV --version
        codecov --required --gcov-exec "$GCOV" --gcov-root ~/build

  install-solidity-mac: &install-solidity-mac
    run:
      name: "Install solidity"
      command: |
        brew update
        brew install wget
        wget -O boost_1_67_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.gz/download
        tar xzvf boost_1_67_0.tar.gz
        cd boost_1_67_0
        ./bootstrap.sh
        sudo ./b2 install
        cd ..
        git clone https://github.com/ethereum/solidity.git
        cd solidity
        mkdir build
        cd build
        cmake .. -DLLL=1 -DUSE_Z3=0
        sudo make install lllc -j $BUILD_PARALLEL_JOBS
  install-solidity: &install-solidity
    run:
      name: "Install solidity"
      command: |
        sudo apt-get update
        sudo apt-get -y install wget python-dev
        wget -O boost_1_67_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.gz/download
        tar xzvf boost_1_67_0.tar.gz
        cd boost_1_67_0
        ./bootstrap.sh
        sudo ./b2 install
        cd ..
        git clone https://github.com/ethereum/solidity.git
        cd solidity
        mkdir build
        cd build
        cmake .. -DLLL=1 -DUSE_Z3=0 -DTESTS=0
        sudo make install lllc -j $BUILD_PARALLEL_JOBS
        
  linux-steps: &linux-steps
    - checkout
    - *environment-info
    - *configure
#    - *upload-hunter-cache
#    - *install-solidity
    - *linuxInstallGO
    - *build
    - *store-retesteth
    - *store-log
    - *test
    - *test-retesteth
#    - *upload-coverage-data

  mac-steps: &mac-steps
      - checkout
      - run:
          name: "Install macOS dependencies"
          # Python3 and requests are needed for Hunter upload.
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install -q cmake ninja git
            git clone --depth 1 https://github.com/ethereum/go-ethereum.git
            git clone --depth 1 https://github.com/ethereum/tests.git

            curl -L https://go.dev/dl/go1.20.1.darwin-amd64.pkg -o go1.20.pkg
            chmod +x go1.20.pkg
            sudo installer -pkg go1.20.pkg -target /
            sudo ln -s /usr/local/go/bin/go /usr/local/bin

            cd go-ethereum
            make all
            ln -s ~/project/go-ethereum/build/bin/evm /usr/local/bin/evm

      - *environment-info
      - *configureMac
#      - *install-solidity-mac
      - *build
      - *store-retesteth
      - *store-log
      - *test
      - *test-retesteth
#      - *upload-coverage-data


version: 2
jobs:

  Linux-Clang11:
    environment:
      - BUILD_TYPE: Release
      - CXX: clang++
      - CC:  clang
      - GCOV: llvm-cov gcov
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 8
      - TEST_PARALLEL_JOBS: 8
    docker:
      - image: ethereum/cpp-build-env:18-clang-11
    steps: *linux-steps

  Linux-GCC9:
    environment:
      - BUILD_TYPE: Release
      - CXX: g++-9
      - CC:  gcc-9
      - GCOV: gcov-9
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 4
      - TEST_PARALLEL_JOBS: 4
      # TODO: Fix memory leaks reported in leveldb.
      # - CMAKE_OPTIONS: -DSANITIZE=address
      # - ASAN_OPTIONS: detect_leaks=0
    docker:
      - image: ethereum/cpp-build-env:18-gcc-9
    steps: *linux-steps

  Linux-GCC12:
    environment:
      - BUILD_TYPE: Release
      - CXX: g++-12
      - CC:  gcc-12
      - GCOV: gcov-12
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 4
      - TEST_PARALLEL_JOBS: 4
    docker:
      - image: ethereum/cpp-build-env:19-gcc-12
    steps: *linux-steps

  macOS-XCode14:
    environment:
      - BUILD_TYPE: Release
      - CXX: clang++
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 4
      - TEST_PARALLEL_JOBS: 4
    macos:
      xcode: "14.2.0"
    steps: *mac-steps

# TODO: Run GCC6 build only in develop branch.
# TODO: Enabled nightly builds and add more configs.
# TODO: Separate builds from testing jobs.
workflows:
  version: 2
  cpp-ethereum:
    jobs:
      - macOS-XCode14
      - Linux-Clang11
      - Linux-GCC9
      - Linux-GCC12
